// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions web = FirebaseOptions(
    apiKey: dotenv.get('FIREBASE_WEB'),
    appId: '1:322581622666:web:8239599d20063c8f4ba273',
    messagingSenderId: '322581622666',
    projectId: 'classesapp-c2170',
    authDomain: 'classesapp-c2170.firebaseapp.com',
    storageBucket: 'classesapp-c2170.appspot.com',
    measurementId: 'G-KWK2PYGLZ7',
  );

  static FirebaseOptions android = FirebaseOptions(
    apiKey: dotenv.get('FIREBASE_ANDROID'),
    appId: '1:322581622666:android:46e3fe81c5425cdb4ba273',
    messagingSenderId: '322581622666',
    projectId: 'classesapp-c2170',
    storageBucket: 'classesapp-c2170.appspot.com',
  );

  static FirebaseOptions ios = FirebaseOptions(
    apiKey: dotenv.get('FIREBASE_IOS'),
    appId: '1:322581622666:ios:8d0a457ad64efe6b4ba273',
    messagingSenderId: '322581622666',
    projectId: 'classesapp-c2170',
    storageBucket: 'classesapp-c2170.appspot.com',
    iosBundleId: 'com.example.classesApplication',
  );

  static FirebaseOptions macos = FirebaseOptions(
    apiKey: dotenv.get("FIREBASE_MACOS"),
    appId: '1:322581622666:ios:166f64d3cb2025f74ba273',
    messagingSenderId: '322581622666',
    projectId: 'classesapp-c2170',
    storageBucket: 'classesapp-c2170.appspot.com',
    iosBundleId: 'com.example.classesApplication.RunnerTests',
  );
}
